from .login_view import *
from .logout_view import *
from .load_formation_file_view import *
from .load_contract_file_view import *
from .submit_contract_data_view import *
from .submit_formation_data_view import *
from .students_show_view import *
from .student_details_view import *
from .student_create_view import *
from .student_update_view import *
from .student_advancements_view import *
from .user_show_view import *
from .user_create_view import *
from .user_update_view import *
from .formation_create_view import *
from .formation_show_view import *
from .formation_update_view import *
from .formation_details_view import *
from .transfer_students_view import *
from .formation_delete import *
from .profile_view import *
from .change_password_view import *
from .dashboard_view import *
from .student_cancel_view import *