# Generated by Django 5.1.3 on 2024-12-10 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="document",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_registration",
                        message="Ingrese un número de documento válido",
                        regex="^\\d{6,15}$",
                    )
                ],
            ),
        ),
    ]
