# Generated by Django 5.1.3 on 2024-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_student_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
