# Generated by Django 5.1.3 on 2024-12-12 22:13

import management.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_formation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractinfo",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("1", "Apprenticeship Contract"),
                    ("2", "Internship"),
                    ("3", "Employment Relationship"),
                    ("4", "Productive Project"),
                ],
                default="1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cellphone",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="code",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[management.utils.validators.validate_code_length],
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[management.utils.validators.validate_name_contains_letter],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="document",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[management.utils.validators.validate_document],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("1", "Citizenship Card"),
                    ("2", "Identity Card"),
                    ("3", "Special Permit to Stay"),
                ],
                default="1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(
                choices=[
                    ("1", "No Contract"),
                    ("2", "In Tracking"),
                    ("3", "No Tracking"),
                    ("4", "Evaluated"),
                    ("5", "Cancelled"),
                ],
                default="1",
                max_length=2,
            ),
        ),
    ]
