# Generated by Django 5.1.3 on 2024-12-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_alter_contractinfo_contract_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
