# Generated by Django 5.1.4 on 2025-01-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
